Upate Open Studios Site CSS for Mobile
bunnymatic/mau pull request #446
Opened 2024-05-10 20:08 UTC by kneyzberg

### Problem
Currently, the Open studios site when there are no open studios events is not responsive to mobile, and the image does not fit nicely on the mobile screens. 

### Solution
Update CSS to be responsive and get the image and text to fit nicely on smaller screens.

2024-05-11 16:47 UTC, bunnymatic commented
Looks good at that size but what about 550px?  
<img width="541" alt="Screenshot 2024-05-11 at 9 42 11 AM" src="https://github.com/bunnymatic/mau/assets/427380/9f25df8e-5ddc-4800-88b1-c1b5d292983c">


I think this is because the container is fixed at 375 and doesn't center so it hangs out on the left.

I wonder if it might be more responsive with something like:
container : max-width 90% (or 95?)
bg: max-width- 100% (fill the container)
bg-img max-width 375px

this way the container and bg would still try to fill and center themselves.

2024-05-11 16:47 UTC, bunnymatic requested changes
see main comment

2024-05-14 04:06 UTC, kneyzberg commented
Yeah definitely, let me take a look at those suggestions!

2024-06-03 03:23 UTC, bunnymatic approved these changes

2024-06-15 20:13 UTC, merged